export const ADD_TODO = 'ADD_TODO'
export const ADDING_TODO = 'ADDING_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const GET_TODOS = 'GET_TODOS'
export const LOAD_TODOS = 'LOAD_TODOS'
export const CHANGE_STATUS_TODO = 'CHANGE_STATUS_TODO'